### PR TITLE
fix: Update name of the project in the readme and other files

### PR DESCRIPTION
**Pull request by Anavelyz**
## Pull Request description
Update the name of the project in:

- README
- ISSUE_TEMPLATE 
- contributing
- intro

Solve #109 

## Pull Request checklists

This PR is a:
- [ ] bug-fix
- [ ] new feature
- [x] maintenance

About this PR:
- [x] it includes tests.
- [x] the tests are executed on CI.
- [x] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:
- [ ] I have reviewed the changes and it contains no misspelling.
- [ ] The code is well commented, especially in the parts that contain more complexity.
- [ ] New and old tests passed locally.

## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved.

### CODE REVIEW

**Comment by Anavelyz** [comment]
@xmnlab The file in this path  `/.github/ISSUE_TEMPLATE/config.yml` must also be edited?

For the project in general, should the variable names be modified?

**Comment by xmnlab** [comment]
> @xmnlab The file in this path  `/.github/ISSUE_TEMPLATE/config.yml` must also be edited?

That would great! Thanks!!

**Comment by xmnlab** [comment]
@Anavelyz , I a bit late here, really sorry.
as I posted to our discord channel, we have already a definite name for the project.
the name osl-python-template was just a temporary name until we find a real name for the project.

could you help us and change the name of the project to scicookie please?
we need something short that would be easy to remember and run from the command line.

really sorry for this re-work ... it is totally my fault ... really sorry
but I hope that this change will help us to have more attraction as well.

thank you so much for your hard work and thanks for understanding this last-minute change

**Comment by Anavelyz** [comment]
> @Anavelyz , I a bit late here, really sorry. as I posted to our discord channel, we have already a definite name for the project. the name osl-python-template was just a temporary name until we find a real name for the project.
> 
> could you help us and change the name of the project to scicookie please? we need something short that would be easy to remember and run from the command line.
> 
> really sorry for this re-work ... it is totally my fault ... really sorry but I hope that this change will help us to have more attraction as well.
> 
> thank you so much for your hard work and thanks for understanding this last-minute change

No worries!
What naming convention will we use in the documentation: SciCookie, scicookie or Scicookie?

**Comment by xmnlab** [comment]
As a project name SciCookie looks good .. and for package name scicookie

**Comment by xmnlab** [comment]
@Anavelyz if you don't mind I will take this issue to do it myself .. I want to release a package for scicookie today :)
sorry for all the trouble :( it is my fault!

**Pull request closed without merging**
